### ISSUE TITLE
Live example

### ISSUE THREAD

**Issue by heff** [theonion/videojs-endcard#1]
This sounds cool. I tried creating a live example for it, but I don't seem to have it right. Could you help finish it up?
http://jsbin.com/AheWEVi/1/edit

**Comment by shaqq** [comment]
Good ol' GitHub preventing JavaScript hotlinking:

![screen shot 2014-01-28 at 5 17 23 pm](https://f.cloud.github.com/assets/1438493/2025062/7167e9f2-8873-11e3-9d76-a49bb6aaf186.png)

I'll make a GitHub page for this, where you should be able to get it.

In the meantime, if you clone the repo, `example.html` is a working demo, with styling and all.

**Comment by heff** [comment]
ha, bummer. Though it seems to be getting through in Safari. I'll check out example.html

**Comment by shaqq** [comment]
@heff [here's your fiddle](http://jsbin.com/AheWEVi/4/edit) working.

(Careful. It's gonna automatically go to videojs.org unless you comment out `getNextVid`)

Also, check out the github page!

http://theonion.github.io/videojs-endcard/

**Comment by heff** [comment]
Woo! That's awesome, and nice demo text. :) This will definitely come in handy.
